import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head> 
         <link
       rel="stylesheet"
       href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
       />
      </head>
      <body
        className={`${cairo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );  
}



