import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { ToastContainer } from "react-toastify";
import ReactQueryProvider from "./providers/ReactQueryProvider";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import { useAppDispatch, useAppSelector } from "./hooks";
import { decrement, increment } from "@/redux/Slices/counter";
import Counter from "./components/Counter";
import ReduxProvider from "./providers/ReduxProvider";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>

        <ReduxProvider>
          <ReactQueryProvider>

            <Header />

            {children}

            <Footer />

          </ReactQueryProvider>
        </ReduxProvider>

      </body>
    </html>
  )
}



